version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - users_service_1
      - users_service_2
      - orders_service_1
      - orders_service_2
      - products_service_1
      - products_service_2
      - payments_service_1
      - payments_service_2

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  users_service_1:
    build:
      context: ./services/users_service
    container_name: users_service_1
    depends_on:
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: users_service.settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./services/users_service:/app

  users_service_2:
    build:
      context: ./services/users_service
    container_name: users_service_2
    depends_on:
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: users_service.settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./services/users_service:/app

  orders_service_1:
    build:
      context: ./services/orders_service
    container_name: orders_service_1
    depends_on:
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: orders_service.settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./services/orders_service:/app

  orders_service_2:
    build:
      context: ./services/orders_service
    container_name: orders_service_2
    depends_on:
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: orders_service.settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./services/orders_service:/app

  products_service_1:
    build:
      context: ./services/products_service
    container_name: products_service_1
    depends_on:
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: products_service.settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./services/products_service:/app

  products_service_2:
    build:
      context: ./services/products_service
    container_name: products_service_2
    depends_on:
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: products_service.settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./services/products_service:/app

  payments_service_1:
    build:
      context: ./services/payments_service
    container_name: payments_service_1
    depends_on:
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: payments_service.settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./services/payments_service:/app

  payments_service_2:
    build:
      context: ./services/payments_service
    container_name: payments_service_2
    depends_on:
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: payments_service.settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./services/payments_service:/app